javaee-root1/java-demo1-jsf-web/src/main/java/pl/tpolgrabia/trainings/javaee/controllers/HelloController.java
package pl.tpolgrabia.trainings.javaee.controllers;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import pl.tpolgrabia.trainings.javaee.javaeedemo.ejb.TodosDao;
import pl.tpolgrabia.trainings.javaee.javaeedemo.ejb.UserDao;
import pl.tpolgrabia.trainings.javaee.javaeedemo.entities.User;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;
import java.util.List;

@Named
@RequestScoped
public class HelloController {
    private static final Logger logger = LoggerFactory.getLogger(HelloController.class);

    @EJB
    private TodosDao todosDao;

    @EJB
    private UserDao userDao;

    private String message;

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public List<String> getAllTodos() {
        return todosDao.findAll();
    }

    public List<User> getAllUsers() {
        return userDao.findAll();
    }

    public String handleSubmit() {
        logger.info("Hello submit");
        return "index";
    }

    public void handleSimpleAction() {
        logger.info("Hello action");
    }

    @PostConstruct
    public void init() {
        this.message = "Submit me";
    }
}

javaee-root1/java-demo1-jsf-web/src/main/webapp/index.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:jsf="http://xmlns.jcp.org/jsf" xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets">
<head jsf:id="head"><title>JSF 2.2</title></head>
<body jsf:id="body">
<h2>Hello JSF</h2>
<form jsf:id="form">
    <button jsf:action="#{helloController.handleSubmit}">#{helloController.message}</button>
</form>
<button type="button" jsf:action="#{helloController.handleSimpleAction}">
    Action me
    <f:ajax/>
</button>
<ul>
    <ui:repeat value="#{helloController.allTodos}" var="todo">
        <li>#{todo}</li>
    </ui:repeat>
</ul>

<ol>
    <ui:repeat value="#{helloController.allUsers}" var="user">
        <li>#{user.firstName}</li>
    </ui:repeat>
</ol>
</body>
</html>